### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by gvc** [vtex/faststore#1044]
I'm creating this issue to let chime in if this should be an atom/molecule or organism and if it should be implemented on faststore or on base.store.

The Alert component represents the top banner that is used to upsell some promotion or product.

[Figma link](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=18%3A33168) | [PR](https://github.com/vtex/faststore/pull/1020)

**Comment by igorbrasileiro** [comment]
Answering the second question, it would be good to have it inside the Faststore UI, because there are some use cases for this alert (e.g.: top navbar alert [ref](https://storetheme.vtex.com/), and you can put it inside a dialog and it becomes an alertdialog [ref]https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html#ex_label)).

About the first question, it depends on many aspects, however, IMO it seems to be an atom because it doesn't have an atom inside of itself.

**Comment by tlgimenes** [comment]
> About the first question, it depends on many aspects, however, IMO it seems to be an atom because it doesn't have an atom inside of itself.

It has, It has icons inside it, which is an atom. That's why I think this should be a molecule.

**Comment by emersonlaurentino** [comment]
Yes, this should be done on faststore as an molecule

**Comment by hellofanny** [comment]
Closing this issue because we decided to classify it as `molecule`. https://github.com/vtex/faststore/pull/1020
