### ISSUE TITLE
Quantity Selector

### ISSUE THREAD

**Issue by emersonlaurentino** [vtex/faststore#846]
- The component will be composed by the atoms: Button and Input. 
- Where the buttons are responsible for incrementing and decrementing the input value. 
- The user can add the value from the buttons or directly from the input. 
- When the input value is 0, the decrement button must be disabled. 
- We don't need a prop that returns the increment or decrement, only an `onChange` of the input is needed. 
- The component must be prop for default value, value, maximum value, and minimum value.

**Comment by rrbambokian** [comment]
I've been working on this component for a few days... [here](https://github.com/vtex/faststore/tree/feat/number-input) is the branch 🤗 

> Before starting the implementation, I did a quick analysis of [customers who already use faststore](https://github.com/vtex/faststore#whos-using-faststore) looking for a basis to component's definition.

### Context
Currently, the component usage context is basically to allow the products' quantity selection within a defined range. Makes it easy to choose the value with just a few clicks - increment/decrement.

### Anatomy
So, component anatomy is defined by increment and decrement buttons associated with an input referring to the value. Allows the value to be changed either by the buttons or typed directly into the field. Considering the context, it makes sense for the increment/decrement to be unitary.
[This reference](https://www.uiguideline.com/components/number-input) shows the most common UI of this component in some popular design systems.

### Name
And finally, about component naming... I think having 'selector' in the name gives us an idea that it's based on the [`Select` atom](https://github.com/vtex/faststore/tree/master/packages/store-ui/src/atoms/Select), so I renamed it to NumberInput. Changing 'Quantity' to 'Number' is justified because quantity gives me an idea of part of a whole, and there may be an associated dimension, that is, the value presented is semantically numerical but its type isn't necessarily a number, besides giving the idea of being able to be increased/decreased of a non-unitary value. Analyzing the [possible names](https://www.uiguideline.com/components/number-input) of the implemented component, `NumberInput` or variants are the most used.

What do you think about these points? Suggest any changes? 🤔
